"""
RFC 5545 calendar of a person's timetable. Contract: ``timetable/README.md``
§4.5. Generated by hand (no third-party dependency): CRLF line endings,
lines folded at 75 octets, ``TZID=Asia/Shanghai`` with a fixed +08:00
``VTIMEZONE``, one ``VEVENT`` per occurrence and escaped text values.
"""
from __future__ import annotations

from datetime import date, datetime, timedelta, timezone

from timetable.models import AcademicTerm
from timetable.services import get_or_create_settings
from timetable.sources.base import Occurrence, load_sources, occurrence_sort_key

__all__ = ['CALENDAR_NAME', 'TZID', 'build_ics']

CALENDAR_NAME = '元培课表'
TZID = 'Asia/Shanghai'
PRODID = '-//YPPF//Timetable//CN'
UID_DOMAIN = 'timetable.yppf'
LOCAL_OFFSET = timedelta(hours=8)
MAX_LINE_OCTETS = 75

_KIND_LABELS = {
    'course': '学校课程',
    'college': '书院课',
    'activity': '活动',
    'appoint': '预约',
    'custom': '自定义',
    'exam': '考试',
}
_STATUS_LABELS = {
    'canceled': '已取消',
    'checked_in': '已签到',
    'applied': '已报名',
}


def build_ics(person, *, today: date | None = None,
              now: datetime | None = None) -> str:
    """
    The calendar text for ``person``: every occurrence of every enabled
    source in the active terms that have not ended before ``today``.
    ``now`` (used for ``DTSTAMP``) may be naive local or timezone-aware.
    """
    if today is None:
        today = date.today()
    if now is None:
        now = datetime.now(timezone.utc)
    settings = get_or_create_settings(person)
    sources = load_sources()
    terms = [
        term for term in AcademicTerm.objects.filter(is_active=True).order_by('week1_monday')
        if term.end_date() >= today
    ]
    occurrences: list[Occurrence] = []
    for term in terms:
        for source in sources:
            occurrences.extend(
                source.occurrences(person, term, 1, term.total_weeks, settings))
    occurrences = [item for item in occurrences if not item.hidden]
    occurrences.sort(key=occurrence_sort_key)

    stamp = _utc_stamp(now)
    lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        f'PRODID:{PRODID}',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        f'X-WR-CALNAME:{_escape(CALENDAR_NAME)}',
        f'X-WR-TIMEZONE:{TZID}',
        *_vtimezone(),
    ]
    for item in occurrences:
        lines.extend(_vevent(item, stamp))
    lines.append('END:VCALENDAR')
    return ''.join(_fold(line) + '\r\n' for line in lines)


def _vtimezone() -> list[str]:
    return [
        'BEGIN:VTIMEZONE',
        f'TZID:{TZID}',
        f'X-LIC-LOCATION:{TZID}',
        'BEGIN:STANDARD',
        'TZOFFSETFROM:+0800',
        'TZOFFSETTO:+0800',
        'TZNAME:CST',
        'DTSTART:19700101T000000',
        'END:STANDARD',
        'END:VTIMEZONE',
    ]


def _vevent(item: Occurrence, stamp: str) -> list[str]:
    description_parts = [part for part in (
        item.subtitle,
        _KIND_LABELS.get(item.kind, item.kind),
        _STATUS_LABELS.get(item.status, ''),
    ) if part]
    lines = [
        'BEGIN:VEVENT',
        f'UID:{_escape(item.id)}@{UID_DOMAIN}',
        f'DTSTAMP:{stamp}',
        f'DTSTART;TZID={TZID}:{_local_stamp(item.start)}',
        f'DTEND;TZID={TZID}:{_local_stamp(item.end)}',
        f'SUMMARY:{_escape(item.title)}',
    ]
    if item.location:
        lines.append(f'LOCATION:{_escape(item.location)}')
    if description_parts:
        lines.append(f'DESCRIPTION:{_escape(" · ".join(description_parts))}')
    lines.append(f'CATEGORIES:{_escape(_KIND_LABELS.get(item.kind, item.kind))}')
    lines.append('STATUS:CANCELLED' if item.status == 'canceled' else 'STATUS:CONFIRMED')
    lines.append('END:VEVENT')
    return lines


def _local_stamp(value: datetime) -> str:
    return value.strftime('%Y%m%dT%H%M%S')


def _utc_stamp(value: datetime) -> str:
    if value.tzinfo is None:
        # Naive datetimes are local (Asia/Shanghai, USE_TZ is False).
        value = value - LOCAL_OFFSET
    else:
        value = value.astimezone(timezone.utc)
    return value.strftime('%Y%m%dT%H%M%SZ')


def _escape(text: str) -> str:
    """Escape a TEXT value (RFC 5545 §3.3.11)."""
    text = str(text or '')
    text = text.replace('\\', '\\\\').replace(';', '\\;').replace(',', '\\,')
    text = text.replace('\r\n', '\n').replace('\r', '\n').replace('\n', '\\n')
    return text


def _fold(line: str) -> str:
    """Fold a content line at 75 octets without splitting UTF-8 sequences."""
    if len(line.encode('utf-8')) <= MAX_LINE_OCTETS:
        return line
    parts: list[str] = []
    current = ''
    current_octets = 0
    limit = MAX_LINE_OCTETS
    for char in line:
        octets = len(char.encode('utf-8'))
        if current_octets + octets > limit:
            parts.append(current)
            current = char
            current_octets = octets
            limit = MAX_LINE_OCTETS - 1  # continuation lines start with a space
        else:
            current += char
            current_octets += octets
    parts.append(current)
    return '\r\n '.join(parts)
