# Generated by Django 5.2.16 on 2026-09-12 19:33

import django.core.validators
import django.db.models.deletion
import rollout.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_membership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "体验通道成员",
                "verbose_name_plural": "体验通道成员",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="代码和小程序里引用的标识，发布后不要修改",
                        max_length=64,
                        unique=True,
                        verbose_name="功能标识",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="功能名称")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="展示在体验通道页面：这个功能是什么、希望收到哪些反馈",
                        verbose_name="功能说明",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("off", "关闭"),
                            ("internal", "内测（仅白名单）"),
                            ("preview", "体验（白名单、体验通道、定向人群）"),
                            ("rollout", "放量（体验范围之外再按比例）"),
                            ("ga", "全量"),
                        ],
                        default="off",
                        max_length=16,
                        verbose_name="阶段",
                    ),
                ),
                (
                    "percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 到 100，只在「放量」阶段生效；同一账号的结果固定不变",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="放量比例",
                    ),
                ),
                (
                    "audience",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='例如 {"status": [2]} 表示住宿辅导员；写多个字段时须全部满足，同一字段内任一取值即可',
                        validators=[rollout.models.validate_audience],
                        verbose_name="定向人群",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="负责人"
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True,
                        help_text="到期时决定全量、继续体验或下线",
                        null=True,
                        verbose_name="复查日期",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "allow_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="开发组成员、提审测试号等；除「关闭」外的所有阶段都生效",
                        related_name="rollout_allowed_features",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="白名单",
                    ),
                ),
            ],
            options={
                "verbose_name": "灰度功能",
                "verbose_name_plural": "灰度功能",
                "ordering": ["key"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("percent__lte", 100)),
                        name="rollout_feature_percent_lte_100",
                    )
                ],
            },
        ),
    ]
