# Generated by Django 5.0.14 on 2025-08-31 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0002_alter_yqpointrecord_source_type_permissionblacklist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="YQpoint",
        ),
        migrations.DeleteModel(
            name="YQPointRecord",
        ),
    ]
