# Generated by Django 5.0.14 on 2026-01-19 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0002_alter_yqpointrecord_source_type_permissionblacklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWechatProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openid",
                    models.CharField(max_length=64, unique=True, verbose_name="微信id"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="绑定时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wx_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
