# Generated by Django 5.0.1 on 2024-01-26 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("generic", "0002_alter_yqpointrecord_source_type"),
        ("generic", "0002_permissionblacklist"),
    ]

    operations = []
