# Generated by Django 5.0.14 on 2026-01-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0003_userwechatprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userwechatprofile",
            options={"verbose_name": "绑定关系", "verbose_name_plural": "绑定关系"},
        ),
    ]
