# Generated by Django 5.2.13 on 2026-08-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_alter_userwechatprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yqpointrecord',
            name='source_type',
            field=models.SmallIntegerField(choices=[(0, '系统操作'), (1, '每日签到'), (2, '参与活动'), (3, '问题反馈'), (4, '达成成就'), (5, '填写问卷'), (6, '奖池花费'), (7, '奖池补偿'), (8, '生日板投放')], default=0, verbose_name='来源类型'),
        ),
    ]
