# Generated by Django 5.2.16 on 2026-08-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0004_alter_userwechatprofile_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingWebviewTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("webview_login", "WebView 登录")],
                        default="webview_login",
                        max_length=32,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_webview_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "待消费 WebView 登录凭据",
                "verbose_name_plural": "待消费 WebView 登录凭据",
            },
        ),
    ]
