# Generated by Django 5.2.13 on 2026-08-31 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0005_alter_yqpointrecord_source_type'),
        ('generic', '0007_merge_pending_auth_credentials'),
    ]

    operations = [
    ]
