# Generated by Django 4.2.3 on 2023-10-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '学期类型',
                'verbose_name_plural': '学期类型',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='学年的起始年份，如2019-2020学年为2019', verbose_name='学年')),
                ('start_date', models.DateField(verbose_name='开学日期')),
                ('end_date', models.DateField(verbose_name='放假日期')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.semestertype')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
                'unique_together': {('year', 'type')},
            },
        ),
    ]
