# Generated by Django 5.2.16 on 2026-09-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("semester", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("holiday", "放假停课"),
                            ("exam", "停课复习考试"),
                            ("swap", "调休"),
                            ("info", "说明"),
                        ],
                        max_length=16,
                        verbose_name="类型",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(help_text="含当日", verbose_name="结束日期"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="名称")),
                (
                    "follows_weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="仅调休填写：1=周一 … 7=周日",
                        null=True,
                        verbose_name="按星期几的课表上课",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "校历事件",
                "verbose_name_plural": "校历事件",
                "ordering": ["start_date", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_date__lte", models.F("end_date"))),
                        name="semester_calendar_event_date_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("follows_weekday__isnull", True),
                            models.Q(
                                ("follows_weekday__gte", 1), ("follows_weekday__lte", 7)
                            ),
                            _connector="OR",
                        ),
                        name="semester_calendar_event_weekday_range",
                    ),
                ],
            },
        ),
    ]
