# Generated by Django 5.2.16 on 2026-09-09 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PkuAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pku_username",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="北大账号"
                    ),
                ),
                ("verified_at", models.DateTimeField(verbose_name="首次验证时间")),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近登录时间"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近同步时间"
                    ),
                ),
                (
                    "login_failures",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="连续失败次数"
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="锁定至"),
                ),
                (
                    "consent_timetable",
                    models.BooleanField(default=False, verbose_name="同意获取课表"),
                ),
                (
                    "consent_timetable_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="课表授权时间"
                    ),
                ),
                (
                    "consent_grades",
                    models.BooleanField(default=False, verbose_name="同意获取成绩"),
                ),
                (
                    "consent_grades_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="成绩授权时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pku_account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "北大账号绑定",
                "verbose_name_plural": "北大账号绑定",
            },
        ),
        migrations.CreateModel(
            name="PkuPortalSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cookies_encrypted", models.BinaryField(verbose_name="加密的 Cookie")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_ok_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近可用时间"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近检查时间"
                    ),
                ),
                ("invalid", models.BooleanField(default=False, verbose_name="已失效")),
                (
                    "invalid_reason",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="失效原因"
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_session",
                        to="pku_account.pkuaccount",
                        verbose_name="绑定",
                    ),
                ),
            ],
            options={
                "verbose_name": "北大门户会话",
                "verbose_name_plural": "北大门户会话",
            },
        ),
    ]
