# Generated by Django 5.0.11 on 2025-01-23 00:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackType",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        primary_key=True, serialize=False, verbose_name="反馈类型编号"
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="反馈类型名称")),
                (
                    "flexible",
                    models.SmallIntegerField(
                        choices=[
                            (0, "无默认值"),
                            (1, "仅提供组织类型默认值"),
                            (2, "全部提供默认值"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.organization",
                    ),
                ),
                (
                    "org_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.organizationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "#EX.反馈类型",
                "verbose_name_plural": "#EX.反馈类型",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "commentbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.commentbase",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "url",
                    models.URLField(
                        blank=True, default="", max_length=256, verbose_name="相关链接"
                    ),
                ),
                (
                    "issue_status",
                    models.SmallIntegerField(
                        choices=[(0, "草稿"), (1, "已发布"), (2, "已删除")],
                        default=0,
                        verbose_name="发布状态",
                    ),
                ),
                (
                    "read_status",
                    models.SmallIntegerField(
                        choices=[(0, "已读"), (1, "未读")],
                        default=1,
                        verbose_name="阅读情况",
                    ),
                ),
                (
                    "solve_status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "已解决"),
                            (1, "解决中"),
                            (2, "无法解决"),
                            (3, "未标记"),
                        ],
                        default=3,
                        verbose_name="解决进度",
                    ),
                ),
                (
                    "feedback_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="反馈时间"),
                ),
                (
                    "publisher_public",
                    models.BooleanField(default=False, verbose_name="发布者是否公开"),
                ),
                (
                    "org_public",
                    models.BooleanField(default=False, verbose_name="组织是否公开"),
                ),
                (
                    "public_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="组织公开时间"
                    ),
                ),
                (
                    "public_status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "公开"),
                            (1, "未公开"),
                            (2, "撤销公开"),
                            (3, "不予公开"),
                        ],
                        default=1,
                        verbose_name="公开状态",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.organization",
                    ),
                ),
                (
                    "org_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.organizationtype",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.naturalperson",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.feedbacktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "#EX.反馈",
                "verbose_name_plural": "#EX.反馈",
            },
            bases=("app.commentbase",),
        ),
    ]
