# Generated by Django 5.0.11 on 2025-02-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="issue_status",
            field=models.SmallIntegerField(
                choices=[(0, "草稿"), (1, "已发布")], default=0, verbose_name="发布状态"
            ),
        ),
    ]
