# Generated by Django 5.2.16 on 2026-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="client_info",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="提交时的客户端环境（如小程序版本），用于排查问题",
                verbose_name="客户端信息",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="feature_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="灰度功能标识",
            ),
        ),
    ]
