# Generated by Django 5.0.14 on 2025-08-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # 这里只包含基本的模型定义，活动相关的模型将在后续迁移中添加
        migrations.RunPython(migrations.RunPython.noop),
    ]
