# Generated by Django 5.0.10 on 2024-12-28 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Freshman",
        ),
    ]
