# Generated by Django 3.2.5 on 2021-07-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationtype',
            old_name='职务名称列表',
            new_name='ojob_name_list',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='ostatus',
        ),
        migrations.AddField(
            model_name='organization',
            name='ointroduction',
            field=models.TextField(blank=True, null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='URL',
            field=models.URLField(blank=True, null=True, verbose_name='相关网址'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='pclass',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='pdorm',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='宿舍'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='pemail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='pgender',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='pmajor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='pnickname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='ptel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='pyear',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='年级'),
        ),
    ]
