# Generated by Django 5.0.9 on 2025-01-05 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        # 这个迁移文件是为了匹配数据库中的迁移记录
        # 实际的字段重命名操作可能已经在数据库中完成
        migrations.RunPython(migrations.RunPython.noop),
    ]
