# Generated by Django 5.0.9 on 2025-01-05 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_delete_freshman"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modifyorganization",
            name="tags",
        ),
    ]
