# Generated by Django 3.2.5 on 2021-07-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210715_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='otype_id',
            new_name='otype',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='oschool_semester',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='oschool_year',
        ),
        migrations.AddField(
            model_name='organization',
            name='ostatus',
            field=models.BooleanField(default=False, verbose_name='激活状态'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='oincharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.naturalperson'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ointroduction',
            field=models.TextField(blank=True, default='这里暂时没有介绍哦~', null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='oname',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
