# Generated by Django 4.2.5 on 2023-10-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='person_id',
            new_name='person',
        ),
    ]
