# Generated by Django 3.2.5 on 2021-07-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210716_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='otype',
            new_name='otype_id',
        ),
    ]
