# Generated by Django 5.0.14 on 2025-08-30 16:40

import app.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_modifyorganization_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "commentbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.commentbase",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="活动名称")),
                (
                    "year",
                    models.IntegerField(
                        default=app.models.current_year, verbose_name="活动年份"
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("Fall", "秋"),
                            ("Spring", "春"),
                            ("Fall+Spring", "春秋"),
                        ],
                        default=app.models.current_semester,
                        max_length=15,
                        verbose_name="活动学期",
                    ),
                ),
                (
                    "publish_day",
                    models.SmallIntegerField(
                        default=3, verbose_name="信息发布提前时间"
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="信息发布时间"
                    ),
                ),
                (
                    "need_apply",
                    models.BooleanField(default=False, verbose_name="是否需要报名"),
                ),
                (
                    "endbefore",
                    models.SmallIntegerField(
                        choices=[(0, "一小时"), (1, "一天"), (2, "三天"), (3, "一周")],
                        default=1,
                        verbose_name="报名截止于",
                    ),
                ),
                (
                    "apply_end",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        verbose_name="报名截止时间",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        verbose_name="活动开始时间",
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        verbose_name="活动结束时间",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="活动地点"
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True, max_length=225, verbose_name="活动简介"
                    ),
                ),
                ("QRcode", models.ImageField(blank=True, upload_to="QRcode/")),
                (
                    "bidding",
                    models.BooleanField(default=False, verbose_name="是否投点竞价"),
                ),
                (
                    "need_checkin",
                    models.BooleanField(default=False, verbose_name="是否需要签到"),
                ),
                (
                    "visit_times",
                    models.IntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "recorded",
                    models.BooleanField(default=False, verbose_name="是否预报备"),
                ),
                (
                    "valid",
                    models.BooleanField(default=False, verbose_name="是否已审核"),
                ),
                ("inner", models.BooleanField(default=False, verbose_name="内部活动")),
                (
                    "capacity",
                    models.IntegerField(default=100, verbose_name="活动最大参与人数"),
                ),
                (
                    "current_participants",
                    models.IntegerField(default=0, verbose_name="活动当前报名人数"),
                ),
                (
                    "URL",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="活动相关(推送)网址",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("审核中", "Reviewing"),
                            ("已撤销", "Abort"),
                            ("未过审", "Reject"),
                            ("已取消", "Canceled"),
                            ("报名中", "Applying"),
                            ("待发布", "Unpublished"),
                            ("等待中", "Waiting"),
                            ("进行中", "Progressing"),
                            ("已结束", "End"),
                        ],
                        default="审核中",
                        max_length=32,
                        verbose_name="活动状态",
                    ),
                ),
                (
                    "category",
                    models.SmallIntegerField(
                        choices=[(0, "普通活动"), (1, "课程活动")],
                        default=0,
                        verbose_name="活动类别",
                    ),
                ),
                (
                    "examine_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.naturalperson",
                        verbose_name="审核老师",
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "3.活动",
                "verbose_name_plural": "3.活动",
            },
            bases=("app.commentbase",),
        ),
        migrations.CreateModel(
            name="ActivityPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[(0, "预告图片"), (1, "总结图片")]
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="activity/photo/%Y/%m/",
                        verbose_name="活动图片",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="app.activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "3.活动图片",
                "verbose_name_plural": "3.活动图片",
                "ordering": ["-time"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("申请中", "Applying"),
                            ("活动申请失败", "Applyfailed"),
                            ("已报名", "Applysuccess"),
                            ("已参与", "Attended"),
                            ("未签到", "Unattended"),
                            ("放弃", "Canceled"),
                        ],
                        default="申请中",
                        max_length=32,
                        verbose_name="学生参与活动状态",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="app.activity",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="app.naturalperson",
                    ),
                ),
            ],
            options={
                "verbose_name": "3.活动参与情况",
                "verbose_name_plural": "3.活动参与情况",
                "ordering": ["activity_id"],
            },
        ),
    ]
