# Generated by Django 5.0.14 on 2025-08-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_modifyorganization_tags"),
        ("app", "0003_rename_activity_id_participant_activity_and_more"),
    ]

    operations = []
