# Generated by Django 4.2.5 on 2023-10-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_activity_id_participant_activity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Participation',
        ),
    ]
