# Generated by Django 5.0.14 on 2025-08-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_merge_20250822_1354"),
    ]

    operations = [
        # 表已经存在，使用空操作跳过
        migrations.RunSQL("SELECT 1", "SELECT 1"),
    ]
