# Generated by Django 5.0.1 on 2024-01-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_participation_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="empty_YQPoint_compensation_lowerbound",
            field=models.IntegerField(default=0, verbose_name="空盒元气值补偿下限"),
        ),
        migrations.AddField(
            model_name="pool",
            name="empty_YQPoint_compensation_upperbound",
            field=models.IntegerField(default=0, verbose_name="空盒元气值补偿上限"),
        ),
        migrations.AddField(
            model_name="poolitem",
            name="is_empty_prize",
            field=models.BooleanField(default=False, verbose_name="是否空盒"),
        ),
    ]
