# Generated by Django 5.0.1 on 2024-08-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_pool_empty_yqpoint_compensation_lowerbound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poolitem",
            name="exchange_attributes",
            field=models.JSONField(default=list, verbose_name="属性"),
        ),
        migrations.AddField(
            model_name="poolrecord",
            name="attributes",
            field=models.JSONField(default=dict, verbose_name="属性"),
        ),
    ]
