# Generated by Django 5.0.1 on 2024-08-31 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_poolitem_exchange_attributes_poolrecord_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.activity",
            ),
        ),
        migrations.AlterField(
            model_name="poolitem",
            name="exchange_attributes",
            field=models.JSONField(blank=True, default=list, verbose_name="属性"),
        ),
        migrations.AlterField(
            model_name="poolrecord",
            name="attributes",
            field=models.JSONField(blank=True, default=dict, verbose_name="属性"),
        ),
    ]
