# Generated by Django 5.0.9 on 2025-01-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_pool_activity_alter_poolitem_exchange_attributes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturalperson",
            name="course_priority",
            field=models.FloatField(default=1.0, verbose_name="书院课选课权重"),
        ),
        migrations.AddConstraint(
            model_name="courseparticipant",
            constraint=models.UniqueConstraint(
                fields=("course", "person"), name="Unique course selection record"
            ),
        ),
    ]
