# Generated by Django 5.0.9 on 2025-01-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_pool_activity_alter_poolitem_exchange_attributes_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="courseparticipant",
            constraint=models.UniqueConstraint(
                fields=("course", "person"), name="Unique course selection record"
            ),
        ),
    ]
