# Generated by Django 5.0.11 on 2025-02-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_courseparticipant_unique_course_selection_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "redirect_url",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="跳转URL"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="homepage_image/", verbose_name="图片"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="图片说明"
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "sort_id",
                    models.SmallIntegerField(default=0, verbose_name="展示顺序"),
                ),
                (
                    "activated",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "首页图片",
                "verbose_name_plural": "首页图片",
            },
        ),
    ]
