# Generated by Django 5.0.9 on 2025-01-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_courseparticipant_unique_course_selection_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturalperson",
            name="course_priority",
            field=models.FloatField(default=1.0, verbose_name="书院课选课权重"),
        ),
    ]
