# Generated by Django 5.0.11 on 2025-02-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_courseparticipant_unique_course_selection_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "redirect_url",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="跳转URL"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="guidepics/", verbose_name="图片"),
                ),
            ],
            options={
                "verbose_name": "首页图片",
                "verbose_name_plural": "首页图片",
            },
        ),
    ]
