# Generated by Django 5.0.14 on 2025-07-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_course_hours_per_class_courserecord_bonus_hours_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("person", "org", "semester", "year"),
                name="Unique position per person, org, semester, year",
            ),
        ),
    ]
