# Generated by Django 5.0.14 on 2025-09-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_position_unique_position_per_person_org_semester_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="academictextentry",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="为空或null表示至今",
                null=True,
                verbose_name="结束日期",
            ),
        ),
        migrations.AddField(
            model_name="academictextentry",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="开始日期"),
        ),
    ]
