# Generated by Django 5.0.14 on 2025-08-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_position_unique_position_per_person_org_semester_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="naturalperson",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "在读/在职"),
                    (1, "住宿辅导员"),
                    (2, "延毕"),
                    (3, "休学"),
                    (4, "已毕业/退休"),
                ],
                default=0,
                verbose_name="在校状态",
            ),
        ),
    ]
