# Generated by Django 5.0.14 on 2025-09-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_naturalperson_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="naturalperson",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "在读/在职"),
                    (1, "已毕业/退休"),
                    (2, "住宿辅导员"),
                    (3, "延毕"),
                    (4, "休学"),
                ],
                default=0,
                verbose_name="在校状态",
            ),
        ),
    ]
