# Generated by Django 5.0.14 on 2026-02-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_naturalperson_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturalperson",
            name="permissions",
            field=models.JSONField(default=dict),
        ),
    ]
