# Generated by Django 5.0.14 on 2026-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_naturalperson_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturalperson",
            name="course_permission",
            field=models.BooleanField(default=False, verbose_name="选课权限"),
        ),
        migrations.AddField(
            model_name="naturalperson",
            name="underground_permission",
            field=models.BooleanField(default=False, verbose_name="地下室权限"),
        ),
        migrations.AddField(
            model_name="naturalperson",
            name="credit_permission",
            field=models.BooleanField(default=False, verbose_name="获得书院课学时权限"),
        ),
    ]
