# Generated by Django 5.0.14 on 2026-02-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_naturalperson_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "德"),
                    (1, "智"),
                    (2, "体"),
                    (3, "美"),
                    (4, "劳"),
                    (5, "其他"),
                ],
                verbose_name="课程类型",
            ),
        ),
    ]
