# Generated by Django 5.0.14 on 2026-01-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_naturalperson_course_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturalperson",
            name="underground_permission",
            field=models.BooleanField(default=False, verbose_name="地下室权限"),
        ),
    ]
