# Generated by Django 5.0.14 on 2026-02-04 20:41 and edited to initialize default permissions

from django.db import migrations, models

from app.config import PERMISSIONS_LIST

def initialize_permissions(apps, schema_editor):
    NaturalPerson = apps.get_model("app", "NaturalPerson")
    
    for person in NaturalPerson.objects.all():
        if not person.permissions:
            person.permissions = {}
        
        for perm_name in PERMISSIONS_LIST:
            # Replicate init_permission logic
            if perm_name == 'select_course' or perm_name == 'underground_appointment':
                # 老师、住宿辅导员、在读、延毕学生有选课权限和地下室预约权限
                # Identity.TEACHER = 0, Identity.STUDENT = 1
                # GraduateStatus.UNDERGRADUATED = 0, GRADUATED = 1, INSTRUCTOR = 2, POSTPONED = 3
                has_permission = (
                    (person.identity == 0 and person.status != 1) or  # TEACHER who's not retired
                    (person.identity == 1 and person.status in [0, 2, 3])  # STUDENT with certain statuses
                )
                person.permissions[perm_name] = has_permission
            elif perm_name == 'gain_credit':
                # 在读、延毕学生有获得书院课学时权限
                # Identity.STUDENT = 1
                # GraduateStatus.UNDERGRADUATED = 0, POSTPONED = 3
                has_permission = (
                    person.identity == 1 and person.status in [0, 3]  # STUDENT with certain statuses
                )
                person.permissions[perm_name] = has_permission
            else:
                # Default value for other permissions
                person.permissions[perm_name] = False
        
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_course_type_add_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturalperson",
            name="permissions",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(
            code = initialize_permissions,
            reverse_code = migrations.RunPython.noop
        )
    ]
