# Generated by Django 5.0.14 on 2026-01-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_naturalperson_underground_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturalperson",
            name="credit_permission",
            field=models.BooleanField(default=False, verbose_name="获得书院课学时权限"),
        ),
    ]
