# Generated by Django 5.2.16 on 2026-08-08 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_naturalperson_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='课程名称')),
                ('teacher', models.CharField(blank=True, default='', max_length=80, verbose_name='教师')),
                ('room', models.CharField(blank=True, default='', max_length=60, verbose_name='教室')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], verbose_name='星期几')),
                ('start_section', models.SmallIntegerField(verbose_name='起始节次')),
                ('end_section', models.SmallIntegerField(verbose_name='结束节次')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('week_start', models.SmallIntegerField(verbose_name='起始周')),
                ('week_end', models.SmallIntegerField(verbose_name='结束周')),
                ('parity', models.SmallIntegerField(choices=[(0, '每周'), (1, '单周'), (2, '双周')], default=0, verbose_name='单双周')),
                ('semester_start', models.DateField(verbose_name='学期第一周周一')),
                ('term', models.CharField(blank=True, default='', max_length=20, verbose_name='学期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_courses', to='app.naturalperson', verbose_name='所属同学')),
            ],
            options={
                'verbose_name': '5.教务课表',
                'verbose_name_plural': '5.教务课表',
                'ordering': ['day_of_week', 'start_section'],
            },
        ),
    ]
