# Generated by Django 5.2.16 on 2026-08-06 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_naturalperson_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileTagCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="分类名称")),
                (
                    "slug",
                    models.SlugField(max_length=48, unique=True, verbose_name="分类标识"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="可用")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="app.profiletagcategory",
                        verbose_name="上级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "P.个人画像标签分类",
                "verbose_name_plural": "P.个人画像标签分类",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProfileTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=24, verbose_name="标签名称")),
                (
                    "normalized_name",
                    models.CharField(
                        editable=False, max_length=24, verbose_name="规范化名称"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("official", "官方候选"), ("custom", "用户自定义")],
                        default="custom",
                        max_length=16,
                        verbose_name="来源",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("interest", "兴趣候选"),
                            ("skill", "技能候选"),
                            ("both", "兴趣与技能"),
                        ],
                        default="interest",
                        max_length=16,
                        verbose_name="适用类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("visible", "正常展示"), ("hidden", "管理员隐藏")],
                        default="visible",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_profile_tags",
                        to="app.naturalperson",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tags",
                        to="app.profiletagcategory",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "P.个人画像标签",
                "verbose_name_plural": "P.个人画像标签",
                "ordering": ["category__sort_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonProfileTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("interest", "兴趣"), ("skill", "技能")],
                        max_length=16,
                        verbose_name="类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="选择时间"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_tag_selections",
                        to="app.naturalperson",
                        verbose_name="人员",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_selections",
                        to="app.profiletag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "P.个人画像标签选择",
                "verbose_name_plural": "P.个人画像标签选择",
                "ordering": ["kind", "created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "tag", "kind"),
                        name="unique_person_profile_tag_kind",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="profiletagcategory",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"),
                name="unique_profile_tag_category_under_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="profiletag",
            constraint=models.UniqueConstraint(
                fields=("category", "normalized_name"),
                name="unique_profile_tag_name_per_category",
            ),
        ),
    ]
