# Generated by Django 5.2.16 on 2026-08-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_passwordresetchallenge_passwordresetthrottle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetchallenge",
            name="expires_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="passwordresetthrottle",
            name="window_started_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
