# Generated by Django 5.2.16 on 2026-08-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_academic_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('category', models.IntegerField(choices=[(1, '日程'), (2, '待办')], default=1, verbose_name='类型')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='地点')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='备注')),
                ('color', models.CharField(default='#16a085', max_length=7, verbose_name='颜色')),
                ('done', models.BooleanField(default=False, verbose_name='已完成')),
                ('repeat', models.IntegerField(choices=[(0, '不重复'), (1, '每天'), (2, '每周')], default=0, verbose_name='重复')),
                ('repeat_end', models.DateField(blank=True, null=True, verbose_name='重复结束日期')),
                ('series_id', models.CharField(blank=True, default='', max_length=32, verbose_name='系列标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.naturalperson', verbose_name='所属同学')),
            ],
            options={
                'verbose_name': '手动日程',
                'verbose_name_plural': '手动日程',
                'ordering': ['date', 'start_time', 'id'],
            },
        ),
    ]
