# Generated by Django 5.2.16 on 2026-08-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_seed_official_profile_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="personprofiletag",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="文字说明"
            ),
        ),
        migrations.AddField(
            model_name="personprofiletag",
            name="description_status",
            field=models.CharField(
                choices=[("visible", "正常展示"), ("hidden_by_admin", "管理员隐藏")],
                default="visible",
                max_length=24,
                verbose_name="文字状态",
            ),
        ),
        migrations.AddField(
            model_name="personprofiletag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.CreateModel(
            name="ParticipationStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=500, verbose_name="文字说明"
                    ),
                ),
                (
                    "description_status",
                    models.CharField(
                        choices=[
                            ("visible", "正常展示"),
                            ("hidden_by_admin", "管理员隐藏"),
                        ],
                        default="visible",
                        max_length=24,
                        verbose_name="文字状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "participation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story",
                        to="app.participation",
                        verbose_name="活动参与记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "3.个人活动记录",
                "verbose_name_plural": "3.个人活动记录",
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ParticipationStoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="profile/activity/%Y/%m/", verbose_name="图片"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("visible", "正常展示"),
                            ("hidden_by_admin", "管理员隐藏"),
                        ],
                        default="visible",
                        max_length=24,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.participationstory",
                        verbose_name="活动记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "3.个人活动记录图片",
                "verbose_name_plural": "3.个人活动记录图片",
                "ordering": ["sort_order", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonProfileTagImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="profile/tag/%Y/%m/", verbose_name="图片"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("visible", "正常展示"),
                            ("hidden_by_admin", "管理员隐藏"),
                        ],
                        default="visible",
                        max_length=24,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.personprofiletag",
                        verbose_name="标签选择",
                    ),
                ),
            ],
            options={
                "verbose_name": "P.个人画像标签图片",
                "verbose_name_plural": "P.个人画像标签图片",
                "ordering": ["sort_order", "created_at", "id"],
            },
        ),
    ]
