# Generated by Django 5.2.16 on 2026-09-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_user_schedule"),
        ("app", "0019_passwordresetchallenge_password_digest"),
    ]

    operations = []
