# Generated by Django 5.2.16 on 2026-08-07 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_activity_story_interactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonProfileTagComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=300, verbose_name="评论内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("visible", "正常展示"),
                            ("hidden_by_admin", "管理员隐藏"),
                        ],
                        default="visible",
                        max_length=24,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_story_comments",
                        to="app.naturalperson",
                        verbose_name="评论人",
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_comments",
                        to="app.personprofiletag",
                        verbose_name="技能记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "P.个人技能记录评论",
                "verbose_name_plural": "P.个人技能记录评论",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonProfileTagLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_story_likes",
                        to="app.naturalperson",
                        verbose_name="点赞人",
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="app.personprofiletag",
                        verbose_name="技能记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "P.个人技能记录点赞",
                "verbose_name_plural": "P.个人技能记录点赞",
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("selection", "person"),
                        name="unique_person_profile_tag_like",
                    )
                ],
            },
        ),
    ]
