# Generated by Django 5.0.11 on 2025-01-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appoint",
            fields=[
                (
                    "Aid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="预约编号"
                    ),
                ),
                (
                    "Atime",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                ("Astart", models.DateTimeField(verbose_name="开始时间")),
                ("Afinish", models.DateTimeField(verbose_name="结束时间")),
                (
                    "Ausage",
                    models.CharField(max_length=256, null=True, verbose_name="用途"),
                ),
                (
                    "Aannouncement",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="预约通知"
                    ),
                ),
                (
                    "Anon_yp_num",
                    models.IntegerField(default=0, verbose_name="外院人数"),
                ),
                ("Ayp_num", models.IntegerField(default=0, verbose_name="院内人数")),
                (
                    "Acheck_status",
                    models.SmallIntegerField(
                        choices=[(0, "Failed"), (1, "Passed"), (2, "Unsaved")],
                        default=2,
                        verbose_name="检测状态",
                    ),
                ),
                (
                    "Astatus",
                    models.IntegerField(
                        choices=[
                            (0, "已取消"),
                            (1, "已预约"),
                            (2, "进行中"),
                            (3, "等待确认"),
                            (4, "已确认"),
                            (5, "违约"),
                            (6, "申诉成功"),
                        ],
                        default=1,
                        verbose_name="预约状态",
                    ),
                ),
                ("Aneed_num", models.IntegerField(verbose_name="检查人数要求")),
                (
                    "Acamera_check_num",
                    models.IntegerField(default=0, verbose_name="检查次数"),
                ),
                (
                    "Acamera_ok_num",
                    models.IntegerField(default=0, verbose_name="人数合格次数"),
                ),
                (
                    "Areason",
                    models.IntegerField(
                        choices=[
                            (0, "没有违约"),
                            (1, "迟到"),
                            (2, "人数不足"),
                            (3, "其它原因"),
                        ],
                        default=0,
                        verbose_name="违约原因",
                    ),
                ),
                (
                    "Atype",
                    models.SmallIntegerField(
                        choices=[
                            (0, "常规预约"),
                            (1, "当天预约"),
                            (2, "临时预约"),
                            (3, "长期预约"),
                            (4, "面试预约"),
                        ],
                        default=0,
                        verbose_name="预约类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "预约信息",
                "verbose_name_plural": "预约信息",
                "ordering": ["Aid"],
                "permissions": [
                    ("create_appointment", "创建预约"),
                    ("cancel_appointment", "取消预约"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CardCheckInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Cardtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="刷卡时间"),
                ),
                (
                    "CardStatus",
                    models.SmallIntegerField(
                        choices=[(0, "不开门"), (1, "开门")],
                        default=0,
                        verbose_name="刷卡状态",
                    ),
                ),
                (
                    "Message",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="记录信息"
                    ),
                ),
            ],
            options={
                "verbose_name": "刷卡记录",
                "verbose_name_plural": "刷卡记录",
            },
        ),
        migrations.CreateModel(
            name="College_Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show",
                    models.SmallIntegerField(
                        choices=[(1, "Yes"), (0, "No")],
                        default=0,
                        verbose_name="是否显示",
                    ),
                ),
                (
                    "announcement",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="通知内容"
                    ),
                ),
            ],
            options={
                "verbose_name": "全院公告",
                "verbose_name_plural": "全院公告",
            },
        ),
        migrations.CreateModel(
            name="LongTermAppoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("times", models.SmallIntegerField(default=1, verbose_name="预约次数")),
                (
                    "interval",
                    models.SmallIntegerField(default=1, verbose_name="间隔周数"),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, default="", verbose_name="评论意见"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "审核中"),
                            (1, "已取消"),
                            (2, "已通过"),
                            (3, "未通过"),
                        ],
                        default=0,
                        verbose_name="申请状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "长期预约信息",
                "verbose_name_plural": "长期预约信息",
            },
        ),
    ]
