# Generated by Django 5.0.11 on 2025-01-23 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Appointment", "0001_initial"),
        ("generic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "Sid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                        verbose_name="学号",
                    ),
                ),
                ("hidden", models.BooleanField(default=False, verbose_name="不可搜索")),
                (
                    "longterm",
                    models.BooleanField(default=False, verbose_name="可长期预约"),
                ),
                (
                    "agree_time",
                    models.DateField(
                        blank=True, null=True, verbose_name="上次许可时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
                "ordering": ["Sid"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "Rid",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="房间编号",
                    ),
                ),
                ("Rtitle", models.CharField(max_length=32, verbose_name="房间名称")),
                (
                    "Rmin",
                    models.IntegerField(default=0, verbose_name="房间预约人数下限"),
                ),
                (
                    "Rmax",
                    models.IntegerField(default=20, verbose_name="房间使用人数上限"),
                ),
                ("Rstart", models.TimeField(verbose_name="最早预约时间")),
                ("Rfinish", models.TimeField(verbose_name="最迟预约时间")),
                (
                    "Rlatest_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="摄像头心跳"),
                ),
                ("Rpresent", models.IntegerField(default=0, verbose_name="目前人数")),
                (
                    "Rstatus",
                    models.SmallIntegerField(
                        choices=[(0, "允许预约"), (1, "无需预约"), (2, "禁止使用")],
                        default=0,
                        verbose_name="房间状态",
                    ),
                ),
                (
                    "RIsAllNight",
                    models.BooleanField(default=False, verbose_name="可通宵使用"),
                ),
                (
                    "RneedAgree",
                    models.BooleanField(default=False, verbose_name="需要许可"),
                ),
            ],
            options={
                "verbose_name": "房间",
                "verbose_name_plural": "房间",
                "ordering": ["Rid"],
            },
        ),
        migrations.AddField(
            model_name="longtermappoint",
            name="appoint",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="Appointment.appoint",
                verbose_name="单次预约信息",
            ),
        ),
        migrations.AddField(
            model_name="longtermappoint",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Appointment.participant",
                verbose_name="申请者",
            ),
        ),
        migrations.AddField(
            model_name="cardcheckinfo",
            name="Cardstudent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Appointment.participant",
                verbose_name="刷卡者",
            ),
        ),
        migrations.AddField(
            model_name="appoint",
            name="major_student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Appointment.participant",
                verbose_name="Appointer",
            ),
        ),
        migrations.AddField(
            model_name="appoint",
            name="students",
            field=models.ManyToManyField(
                db_index=True, related_name="appoint_list", to="Appointment.participant"
            ),
        ),
        migrations.AddField(
            model_name="cardcheckinfo",
            name="Cardroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="Appointment.room",
                verbose_name="房间号",
            ),
        ),
        migrations.AddField(
            model_name="appoint",
            name="Room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appoint_list",
                to="Appointment.room",
                verbose_name="房间号",
            ),
        ),
    ]
