# Generated by Django 5.0.14 on 2025-09-16 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0003_alter_appoint_options_alter_appoint_areason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AI_Inspection_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ireason", models.CharField(max_length=256, verbose_name="事由")),
                (
                    "Iresult",
                    models.SmallIntegerField(
                        choices=[(1, "合规"), (0, "不合规"), (-1, "错误")],
                        default=-1,
                        verbose_name="审核结果",
                    ),
                ),
                (
                    "Idetail",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="审核详情"
                    ),
                ),
                (
                    "Itimestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="审核时间"),
                ),
                (
                    "Iperson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="预约人",
                    ),
                ),
                (
                    "Iroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appointment.room",
                        verbose_name="房间号",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI审核信息",
                "verbose_name_plural": "AI审核信息",
            },
        ),
    ]
