# Generated by Django 5.0.1 on 2024-01-21 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Appointment", "0003_alter_appoint_options_alter_appoint_areason"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appoint",
            options={
                "ordering": ["Aid"],
                "permissions": [("预约地下室", "预约地下室"), ("取消预约", "取消预约")],
                "verbose_name": "预约信息",
                "verbose_name_plural": "预约信息",
            },
        ),
    ]
