# Generated by Django 5.0.9 on 2024-11-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appointment", "0003_alter_appoint_options_alter_appoint_areason"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(
                null=True, upload_to="room_images", verbose_name="房间图片"
            ),
        ),
        migrations.CreateModel(
            name="RoomClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_idx", models.SmallIntegerField(verbose_name="主页排序")),
                (
                    "name",
                    models.CharField(max_length=32, unique=True, verbose_name="类别名称"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="类别描述"
                    ),
                ),
                ("reservable", models.BooleanField(default=True, verbose_name="可预约")),
                (
                    "quick_reservable",
                    models.BooleanField(default=False, verbose_name="临时预约"),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        db_index=True,
                        related_name="classes",
                        to="Appointment.room",
                        verbose_name="房间列表",
                    ),
                ),
            ],
            options={
                "verbose_name": "房间类别",
                "verbose_name_plural": "房间类别",
            },
        ),
    ]
