# Generated by Django 5.0.14 on 2026-01-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0003_alter_appoint_options_alter_appoint_areason"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="underground",
            field=models.BooleanField(default=False, verbose_name="地下室权限"),
        ),
    ]
