# Generated by Django 5.2.16 on 2026-09-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0003_alter_appoint_options_alter_appoint_areason"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="has_read_instructions",
            field=models.BooleanField(
                default=False, verbose_name="已查看地下室使用规范"
            ),
        ),
    ]
