# Generated by Django 5.0.14 on 2026-01-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0004_participant_underground"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="underground",
        ),
    ]
