# Generated by Django 5.0.1 on 2024-01-22 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Appointment", "0004_alter_appoint_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appoint",
            options={
                "ordering": ["Aid"],
                "permissions": [
                    ("create_appointment", "创建预约"),
                    ("cancel_appointment", "取消预约"),
                ],
                "verbose_name": "预约信息",
                "verbose_name_plural": "预约信息",
            },
        ),
    ]
