# Generated by Django 5.0.9 on 2024-12-28 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appointment", "0004_room_image_room_quick_reservable_roomclass"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["Rid"],
                "permissions": [("can_book_example_rooms", "可预约样例房间")],
                "verbose_name": "房间",
                "verbose_name_plural": "房间",
            },
        ),
        migrations.AddField(
            model_name="room",
            name="required_perm",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.permission",
            ),
        ),
    ]
