# Generated by Django 5.0.9 on 2024-12-28 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Appointment", "0005_alter_room_options_room_required_perm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="agree_time",
        ),
    ]
