# Generated by Django 5.0.10 on 2025-02-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0006_remove_participant_agree_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cross_sys_uid',
            field=models.CharField(max_length=32, null=True, verbose_name='跨系统id'),
        ),
        migrations.CreateModel(
            name='EntranceGuard',
            fields=[
                ('door_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='门禁编号')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('port', models.IntegerField(default=8000, verbose_name='端口')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_guards', to='Appointment.room', verbose_name='对应房间')),
            ],
            options={
                'verbose_name': '门禁设备',
                'verbose_name_plural': '门禁设备',
            },
        ),
    ]
