# Generated by Django 5.2.13 on 2026-04-15 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthboardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_username', models.CharField(max_length=64)),
                ('receiver_name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('mode', models.IntegerField()),
                ('per_cost', models.IntegerField()),
                ('image', models.ImageField(upload_to='birthboard_images/')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting_confirm', '等待大家确认'), ('waiting_receiver', '等待寿星确认'), ('ready', '等待投放'), ('ongoing', '投放进行中'), ('finished', '投放完成'), ('terminated', '已终止')], default='waiting_confirm', max_length=32, verbose_name='主流程状态')),
            ],
        ),
        migrations.CreateModel(
            name='BirthboardParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sender', '送出人'), ('receiver', '寿星')], max_length=16)),
                ('is_initiator', models.BooleanField(default=False)),
                ('cost', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('wait', '待确认'), ('confirmed', '已确认'), ('rejected', '已拒绝'), ('paid', '已扣款'), ('refunded', '已退款')], default='wait', max_length=16)),
                ('action_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='birthboard.birthboardrecord')),
            ],
            options={
                'unique_together': {('record', 'user', 'role')},
            },
        ),
    ]
