# Generated by Django 5.2.13 on 2026-08-18 22:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('birthboard', '0002_alter_birthboardrecord_status'), ('birthboard', '0003_alter_birthboardrecord_status'), ('birthboard', '0004_birthboardrejectedissue'), ('birthboard', '0005_birthboardapprover'), ('birthboard', '0006_birthboardrecord_first_approved_and_more'), ('birthboard', '0007_alter_birthboardrecord_status'), ('birthboard', '0008_changerecord'), ('birthboard', '0009_add_contract'), ('birthboard', '0010_add_confirm_seen'), ('birthboard', '0011_add_thumbnail_field')]

    dependencies = [
        ('birthboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthboardrecord',
            name='status',
            field=models.CharField(choices=[('waiting_confirm', '等待大家确认'), ('waiting_receiver', '等待寿星确认'), ('waiting_approve', '等待管理员审批'), ('ready', '等待投放'), ('ongoing', '投放进行中'), ('finished', '投放完成'), ('terminated', '已终止'), ('terminated_by_admin', '被管理员驳回'), ('canceled', '已撤销')], default='waiting_confirm', max_length=32, verbose_name='主流程状态'),
        ),
        migrations.CreateModel(
            name='BirthboardRejectedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.CharField(help_text='多选原因，逗号分隔', max_length=128)),
                ('detail', models.TextField(help_text='具体违规内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_issue', to='birthboard.birthboardrecord')),
            ],
        ),
        migrations.CreateModel(
            name='BirthboardApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', help_text='备注', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthboard_approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='birthboardrecord',
            name='first_approved',
            field=models.BooleanField(default=False, verbose_name='一审已通过'),
        ),
        migrations.AddField(
            model_name='birthboardrecord',
            name='first_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='一审时间'),
        ),
        migrations.AddField(
            model_name='birthboardrecord',
            name='first_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthboard_first_approved', to=settings.AUTH_USER_MODEL, verbose_name='一审人'),
        ),
        migrations.AddField(
            model_name='birthboardrecord',
            name='second_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='二审时间'),
        ),
        migrations.AddField(
            model_name='birthboardrecord',
            name='second_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthboard_second_approved', to=settings.AUTH_USER_MODEL, verbose_name='二审人'),
        ),
        migrations.CreateModel(
            name='BirthboardSecondApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', help_text='备注', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthboard_second_approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('pay', '付款'), ('abort', '中止'), ('revoke', '撤销'), ('reject', '拒绝'), ('approve', '审核通过'), ('refund', '退款'), ('update', '更新')], max_length=16, verbose_name='操作类型')),
                ('before_status', models.CharField(blank=True, default='', max_length=32, verbose_name='修改前状态')),
                ('after_status', models.CharField(blank=True, default='', max_length=32, verbose_name='修改后状态')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='修改信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthboard_change_records', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_records', to='birthboard.birthboardrecord', verbose_name='投放记录')),
            ],
            options={
                'verbose_name': '投放变更记录',
                'verbose_name_plural': '投放变更记录',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BirthboardContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed', models.BooleanField(default=False, verbose_name='已签署')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签署时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthboard_contract', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BirthboardConfirmSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_seen', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 8, 0))),
                ('received_seen', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 8, 0))),
                ('finished_seen', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 8, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthboard_confirm_seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='birthboardrecord',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='birthboard_thumbnails/'),
        ),
    ]
