# Generated by Django 5.2.13 on 2026-07-15 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0008_changerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthboardContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed', models.BooleanField(default=False, verbose_name='已签署')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签署时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthboard_contract', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
