# Generated by Django 5.2.13 on 2026-07-15 18:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0009_add_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthboardConfirmSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_seen', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 8, 0))),
                ('received_seen', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 8, 0))),
                ('finished_seen', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 8, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthboard_confirm_seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
