# Generated by Django 5.2.13 on 2026-07-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0010_add_confirm_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthboardrecord',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='birthboard_thumbnails/'),
        ),
    ]
