# Generated by Django 5.2.12 on 2026-08-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "birthboard",
            "0002_alter_birthboardrecord_status_squashed_0011_add_thumbnail_field",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthboardLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="累计点赞量"),
                ),
            ],
            options={
                "verbose_name": "制作名单点赞量",
                "verbose_name_plural": "制作名单点赞量",
            },
        ),
    ]
