# Generated by Django 5.2.13 on 2026-08-29 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0012_birthboardlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthboardReminderSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='提醒日期')),
                ('reminder_type', models.CharField(max_length=16, verbose_name='提醒类型')),
                ('seen_at', models.DateTimeField(auto_now_add=True, verbose_name='标记时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthboard_reminder_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '生日提醒已读记录',
                'verbose_name_plural': '生日提醒已读记录',
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'reminder_type'), name='uniq_birthboard_reminder_seen')],
            },
        ),
    ]
