# Generated by Django 5.2.13 on 2026-09-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0014_harden_review_and_takedown'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthboardapprover',
            name='reminder_enabled',
            field=models.BooleanField(default=True, verbose_name='接收重复提醒'),
        ),
        migrations.AddField(
            model_name='birthboardsecondapprover',
            name='reminder_enabled',
            field=models.BooleanField(default=True, verbose_name='接收重复提醒'),
        ),
    ]
