# Generated by Django 5.2.13 on 2026-09-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0015_birthboardapprover_reminder_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthboardapprover',
            options={'verbose_name': '初审人员', 'verbose_name_plural': '1.初审人员'},
        ),
        migrations.AlterModelOptions(
            name='birthboardcontract',
            options={'verbose_name': '协议记录', 'verbose_name_plural': '3.协议记录与小黑屋'},
        ),
        migrations.AlterModelOptions(
            name='birthboardrecord',
            options={'verbose_name': '灯牌记录', 'verbose_name_plural': '4.灯牌记录'},
        ),
        migrations.AlterModelOptions(
            name='birthboardsecondapprover',
            options={'verbose_name': '终审人员', 'verbose_name_plural': '2.终审人员'},
        ),
    ]
