# Generated by Django 5.2.13 on 2026-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0016_alter_birthboardapprover_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthboardrecord',
            name='takedown_fail_count',
            field=models.PositiveIntegerField(default=0, verbose_name='下架失败计数'),
        ),
    ]
