# Generated by Django 5.2.13 on 2026-09-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthboard', '0017_birthboardrecord_takedown_fail_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthboardcontract',
            name='protocol_version',
            field=models.PositiveIntegerField(default=0, verbose_name='协议版本'),
        ),
    ]
