# Generated by Django 5.2.16 on 2026-09-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0019_passwordresetchallenge_password_digest"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term_code",
                    models.CharField(
                        help_text="门户 xnd-xq，如 25-26-1",
                        max_length=16,
                        verbose_name="学期代码",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(blank=True, max_length=32, verbose_name="课程号"),
                ),
                (
                    "class_no",
                    models.CharField(blank=True, max_length=8, verbose_name="班号"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="课程名")),
                (
                    "course_type",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="课程类别"
                    ),
                ),
                (
                    "credits",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="学分",
                    ),
                ),
                (
                    "score",
                    models.CharField(blank=True, max_length=16, verbose_name="成绩"),
                ),
                (
                    "score_numeric",
                    models.FloatField(blank=True, null=True, verbose_name="成绩数值"),
                ),
                ("gpa", models.FloatField(blank=True, null=True, verbose_name="绩点")),
                (
                    "raw",
                    models.JSONField(blank=True, default=dict, verbose_name="原始数据"),
                ),
                ("fetched_at", models.DateTimeField(verbose_name="获取时间")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_records",
                        to="app.naturalperson",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "成绩记录",
                "verbose_name_plural": "成绩记录",
                "ordering": ["-term_code", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "term_code", "course_code", "name"),
                        name="academic_record_grade_unique_key",
                    )
                ],
            },
        ),
    ]
