# Generated by Django 4.2.3 on 2023-10-18 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementunlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='achievement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.achievementtype', verbose_name='类型'),
        ),
        migrations.AlterUniqueTogether(
            name='achievementunlock',
            unique_together={('user', 'achievement')},
        ),
    ]
