# Generated by Django 5.2.16 on 2026-09-09 12:13

import django.db.models.deletion
import timetable.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0019_passwordresetchallenge_password_digest"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="学期代码"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="学期名称")),
                ("week1_monday", models.DateField(verbose_name="第一教学周周一")),
                (
                    "total_weeks",
                    models.PositiveSmallIntegerField(default=16, verbose_name="总周数"),
                ),
                (
                    "section_times",
                    models.JSONField(
                        default=timetable.models.default_section_times,
                        help_text='{"1": ["08:00", "08:50"], ...}',
                        verbose_name="节次时间表",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
            ],
            options={
                "verbose_name": "课表学期",
                "verbose_name_plural": "课表学期",
                "ordering": ["-week1_monday"],
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("portal", "门户导入"),
                            ("paste", "粘贴导入"),
                            ("manual", "手动添加"),
                        ],
                        max_length=16,
                        verbose_name="来源",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "成功"), ("failed", "失败")],
                        max_length=8,
                        verbose_name="结果",
                    ),
                ),
                (
                    "entries_count",
                    models.PositiveIntegerField(default=0, verbose_name="条目数"),
                ),
                ("message", models.TextField(blank=True, verbose_name="信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_import_logs",
                        to="app.naturalperson",
                        verbose_name="学生",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_logs",
                        to="timetable.academicterm",
                        verbose_name="学期",
                    ),
                ),
            ],
            options={
                "verbose_name": "课表导入记录",
                "verbose_name_plural": "课表导入记录",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TimetableSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ics_token",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="ICS 令牌"
                    ),
                ),
                (
                    "reminder_enabled",
                    models.BooleanField(default=False, verbose_name="上课提醒"),
                ),
                (
                    "reminder_minutes",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="提前分钟数"
                    ),
                ),
                (
                    "show_college",
                    models.BooleanField(default=True, verbose_name="显示书院课"),
                ),
                (
                    "show_activities",
                    models.BooleanField(default=True, verbose_name="显示活动"),
                ),
                (
                    "show_appointments",
                    models.BooleanField(default=True, verbose_name="显示预约"),
                ),
                (
                    "share_show_name",
                    models.BooleanField(default=True, verbose_name="海报显示姓名"),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_settings",
                        to="app.naturalperson",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "课表设置",
                "verbose_name_plural": "课表设置",
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("portal", "门户导入"),
                            ("paste", "粘贴导入"),
                            ("manual", "手动添加"),
                        ],
                        max_length=16,
                        verbose_name="来源",
                    ),
                ),
                (
                    "external_key",
                    models.CharField(max_length=64, verbose_name="外部键"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="课程名")),
                (
                    "course_code",
                    models.CharField(blank=True, max_length=32, verbose_name="课程号"),
                ),
                (
                    "class_no",
                    models.CharField(blank=True, max_length=16, verbose_name="班号"),
                ),
                (
                    "teacher",
                    models.CharField(blank=True, max_length=100, verbose_name="教师"),
                ),
                (
                    "room",
                    models.CharField(blank=True, max_length=100, verbose_name="教室"),
                ),
                (
                    "weekday",
                    models.SmallIntegerField(
                        help_text="1=周一 … 7=周日", verbose_name="星期"
                    ),
                ),
                ("start_section", models.SmallIntegerField(verbose_name="起始节")),
                ("end_section", models.SmallIntegerField(verbose_name="结束节")),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                ("week_start", models.SmallIntegerField(verbose_name="起始周")),
                ("week_end", models.SmallIntegerField(verbose_name="结束周")),
                (
                    "parity",
                    models.SmallIntegerField(
                        choices=[(0, "每周"), (1, "单周"), (2, "双周")],
                        default=0,
                        verbose_name="单双周",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                ("raw_text", models.TextField(blank=True, verbose_name="原始文本")),
                ("hidden", models.BooleanField(default=False, verbose_name="隐藏")),
                (
                    "color",
                    models.CharField(blank=True, max_length=7, verbose_name="颜色"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="app.naturalperson",
                        verbose_name="学生",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="timetable.academicterm",
                        verbose_name="学期",
                    ),
                ),
            ],
            options={
                "verbose_name": "课表条目",
                "verbose_name_plural": "课表条目",
                "ordering": ["weekday", "start_section", "start_time", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "term", "source", "external_key"),
                        name="timetable_entry_unique_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weekday__gte", 1), ("weekday__lte", 7)),
                        name="timetable_entry_weekday_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("start_section__lte", models.F("end_section"))
                        ),
                        name="timetable_entry_section_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("week_start__lte", models.F("week_end"))),
                        name="timetable_entry_week_order",
                    ),
                ],
            },
        ),
    ]
