# Generated by Django 5.2.16 on 2026-09-09 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_passwordresetchallenge_password_digest"),
        ("timetable", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCatalogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=64, verbose_name="院系"),
                ),
                ("course_code", models.CharField(max_length=32, verbose_name="课程号")),
                ("name", models.CharField(max_length=80, verbose_name="课程名")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="课程英文名"
                    ),
                ),
                (
                    "class_no",
                    models.CharField(blank=True, max_length=8, verbose_name="班号"),
                ),
                (
                    "audience",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="修读对象"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="课程类别"
                    ),
                ),
                (
                    "credits",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="参考学分",
                    ),
                ),
                (
                    "hours_per_week",
                    models.CharField(blank=True, max_length=16, verbose_name="周学时"),
                ),
                (
                    "total_hours",
                    models.CharField(blank=True, max_length=16, verbose_name="总学时"),
                ),
                (
                    "teacher",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="授课教师"
                    ),
                ),
                (
                    "weeks_text",
                    models.CharField(blank=True, max_length=64, verbose_name="起止周"),
                ),
                (
                    "time_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="上课时间"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "slots",
                    models.JSONField(blank=True, default=list, verbose_name="时段"),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_entries",
                        to="timetable.academicterm",
                        verbose_name="学期",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程目录",
                "verbose_name_plural": "课程目录",
                "ordering": ["course_code", "class_no", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("term", "course_code", "class_no"),
                        name="timetable_catalog_entry_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurrence_id",
                    models.CharField(max_length=128, verbose_name="事件标识"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("subscribe", "订阅消息"),
                            ("notification", "站内通知"),
                            ("skipped", "未发送"),
                        ],
                        max_length=16,
                        verbose_name="渠道",
                    ),
                ),
                ("scheduled_for", models.DateTimeField(verbose_name="计划提醒时间")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="处理时间"),
                ),
                (
                    "detail",
                    models.CharField(blank=True, max_length=128, verbose_name="详情"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="app.naturalperson",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "上课提醒记录",
                "verbose_name_plural": "上课提醒记录",
                "ordering": ["-scheduled_for", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "occurrence_id"),
                        name="timetable_reminder_log_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscribeQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_key",
                    models.CharField(max_length=32, verbose_name="模板键"),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="剩余次数"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribe_quotas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "订阅消息配额",
                "verbose_name_plural": "订阅消息配额",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "template_key"),
                        name="timetable_subscribe_quota_unique",
                    )
                ],
            },
        ),
    ]
