# Generated by Django 5.2.16 on 2026-09-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_coursecatalogentry_reminderlog_subscribequota"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetablesettings",
            name="show_courses",
            field=models.BooleanField(default=True, verbose_name="显示学校课表"),
        ),
    ]
