# Generated by Django 5.2.16 on 2026-09-10 10:13
#
# Iteration 3 of the timetable (timetable/README.md §8): catalog links, roles,
# categories and tags on entries, per-week overrides, tag/exam settings, exam
# weeks on terms and the exam schedule. The data step marks existing manual
# entries as category 'other' — they were rendered as 'custom' before, and the
# derived kind must not change for them.

import django.db.models.deletion
from django.db import migrations, models


def manual_entries_to_other(apps, schema_editor):
    TimetableEntry = apps.get_model('timetable', 'TimetableEntry')
    TimetableEntry.objects.filter(source='manual').update(category='other')


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0003_timetablesettings_show_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicterm",
            name="exam_week_start",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="从该周起为考试周；留空表示没有考试周",
                null=True,
                verbose_name="考试周起始周",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="catalog_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_entries",
                to="timetable.coursecatalogentry",
                verbose_name="课程目录",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="category",
            field=models.CharField(
                choices=[("course", "课程"), ("exam", "考试"), ("other", "其它")],
                default="course",
                max_length=16,
                verbose_name="类别",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="role",
            field=models.CharField(
                choices=[("enrolled", "已选"), ("audit", "旁听")],
                default="enrolled",
                max_length=16,
                verbose_name="身份",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="tag",
            field=models.CharField(blank=True, max_length=24, verbose_name="标签"),
        ),
        migrations.AddField(
            model_name="timetablesettings",
            name="hidden_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="带这些标签的条目不在课表中显示",
                verbose_name="隐藏的标签",
            ),
        ),
        migrations.AddField(
            model_name="timetablesettings",
            name="show_exams",
            field=models.BooleanField(default=True, verbose_name="显示考试"),
        ),
        migrations.AlterField(
            model_name="academicterm",
            name="total_weeks",
            field=models.PositiveSmallIntegerField(
                default=16, help_text="含考试周", verbose_name="总周数"
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="note",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.CreateModel(
            name="TimetableEntryOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="留空 = 条目的起始周",
                        null=True,
                        verbose_name="起始周",
                    ),
                ),
                (
                    "week_end",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="留空 = 条目的结束周",
                        null=True,
                        verbose_name="结束周",
                    ),
                ),
                ("canceled", models.BooleanField(default=False, verbose_name="停课")),
                (
                    "fields",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="修改的字段"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="timetable.timetableentry",
                        verbose_name="条目",
                    ),
                ),
            ],
            options={
                "verbose_name": "课表条目修改",
                "verbose_name_plural": "课表条目修改",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CourseExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=32, verbose_name="课程号")),
                (
                    "class_no",
                    models.CharField(blank=True, max_length=8, verbose_name="班号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="课程名")),
                (
                    "teacher",
                    models.CharField(blank=True, max_length=80, verbose_name="教师"),
                ),
                ("start", models.DateTimeField(verbose_name="开始时间")),
                ("end", models.DateTimeField(verbose_name="结束时间")),
                (
                    "room",
                    models.CharField(blank=True, max_length=100, verbose_name="考场"),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="考试方式"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "raw_time",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="原始时间文本"
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="timetable.academicterm",
                        verbose_name="学期",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试安排",
                "verbose_name_plural": "考试安排",
                "ordering": ["start", "course_code", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("term", "course_code", "class_no", "start"),
                        name="timetable_course_exam_unique",
                    )
                ],
            },
        ),
        # Reversal is a no-op: the category column is dropped again by the
        # reversed AddField, so there is nothing to restore.
        migrations.RunPython(manual_entries_to_other, migrations.RunPython.noop),
    ]
