# Generated by Django 5.2.16 on 2026-09-10 18:41
#
# The course table's own exam info on imported entries (timetable/README.md
# §8.4): the 考试信息 date, 上午/下午/晚上 and room, set and refreshed by every
# import. Existing entries stay null/blank until their next import, so no data
# step is needed.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0004_iteration3_catalog_links_overrides_exams"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableentry",
            name="exam_date",
            field=models.DateField(blank=True, null=True, verbose_name="考试日期"),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="exam_period",
            field=models.CharField(
                blank=True,
                choices=[("上午", "上午"), ("下午", "下午"), ("晚上", "晚上")],
                max_length=8,
                verbose_name="考试时段",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="exam_room",
            field=models.CharField(blank=True, max_length=100, verbose_name="考场"),
        ),
    ]
