# Generated by Django 5.0.11 on 2025-01-23 00:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(2, "Module View"), (3, "Module Click")],
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "page",
                    models.URLField(blank=True, max_length=256, verbose_name="页面url"),
                ),
                (
                    "module_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="模块名称"
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="发生时间"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="设备类型"
                    ),
                ),
                (
                    "explore_name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="浏览器类型"
                    ),
                ),
                (
                    "explore_version",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="浏览器版本"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "埋点记录-模块",
                "verbose_name_plural": "埋点记录-模块",
            },
        ),
        migrations.CreateModel(
            name="PageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Page View"), (1, "Page Disappear")],
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "page",
                    models.URLField(blank=True, max_length=256, verbose_name="页面url"),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="发生时间"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="设备类型"
                    ),
                ),
                (
                    "explore_name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="浏览器类型"
                    ),
                ),
                (
                    "explore_version",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="浏览器版本"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "埋点记录-页面",
                "verbose_name_plural": "埋点记录-页面",
            },
        ),
    ]
