# Generated by Django 5.0.11 on 2025-01-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sign_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="签订时间"),
                ),
            ],
            options={
                "verbose_name": "住宿协议",
                "verbose_name_plural": "住宿协议",
            },
        ),
        migrations.CreateModel(
            name="Dormitory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="宿舍号"
                    ),
                ),
                ("capacity", models.IntegerField(default=4, verbose_name="容量")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
            ],
            options={
                "verbose_name": "宿舍",
                "verbose_name_plural": "宿舍",
            },
        ),
        migrations.CreateModel(
            name="DormitoryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_id", models.IntegerField(verbose_name="床位号")),
                (
                    "time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "宿舍分配信息",
                "verbose_name_plural": "宿舍分配信息",
            },
        ),
    ]
