# Generated by Django 5.0.11 on 2025-01-23 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dormitory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="dormitoryassignment",
            name="dormitory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dormitory.dormitory",
                verbose_name="宿舍号",
            ),
        ),
        migrations.AddField(
            model_name="dormitoryassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="成员",
            ),
        ),
    ]
