# Generated by Django 5.0.14 on 2025-08-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dormitory", "0003_agreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="dormitoryassignment",
            name="active",
            field=models.BooleanField(default=True, verbose_name="是否有效"),
        ),
    ]
