# Generated by Django 4.2.3 on 2023-10-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='书籍编号')),
                ('identity_code', models.CharField(blank=True, max_length=254, null=True, verbose_name='索书号')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=254, null=True, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=254, null=True, verbose_name='出版商')),
                ('returned', models.BooleanField(default=True, verbose_name='是否已还')),
            ],
            options={
                'verbose_name': '书',
                'verbose_name_plural': '书',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('student_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='学号')),
            ],
            options={
                'verbose_name': '读者',
                'verbose_name_plural': '读者',
            },
        ),
        migrations.CreateModel(
            name='LendRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='条目编号')),
                ('lend_time', models.DateTimeField(verbose_name='借出时间')),
                ('due_time', models.DateTimeField(verbose_name='还书截止时间')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='还书时间')),
                ('returned', models.BooleanField(default=False, verbose_name='是否已还')),
                ('status', models.SmallIntegerField(choices=[(0, '正常'), (1, '超时扣分'), (2, '申诉中'), (3, '申诉通过'), (4, '申诉失败')], default=0, verbose_name='借阅记录状态')),
                ('book_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yp_library.book', verbose_name='书籍编号')),
                ('reader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yp_library.reader', verbose_name='读者编号')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'ordering': ['-lend_time'],
            },
        ),
    ]
