name: DEV

on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches: [ develop ]

jobs:
  deploy_dev:
    runs-on: self-hosted
    steps:
      - run: bash restart_dev.sh
